# config context path to "/" by setting an empty string
server:
  contextPath:

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
  users:
    - 
      username: api
      password: $2a$04$GoqF.O.UrB.QeLDqVbHeJubqf5JuWjE4LpOlc/s2LS1fCZ1J6hyaO
      authorities: ROLE_USER
        
    - 
      username: admin
      password: $2a$04$Y/DPp3zZElMC8aXT.ARzWeSh.TeccKbZoCQJm73sUFe6dJ8097EXm
      authorities: 
       - ROLE_USER
       - ROLE_ADMIN
  
#logging:
#  level:
#    org.springframework:
#      security: DEBUG

---

spring:
   profiles.active: test
---
   
spring:
  profiles: dev
  
  datasource:
    url: jdbc:mysql://localhost:3306/DB_NAME?useSSL=false
    username: DB_USERS
    password: DB_PASSWORD
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  
---
 
spring:
  profiles: test 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

